### PR TITLE
Remove .env and add dev.secret.exs for config

### LINKED ISSUE #199: Config fails to auto-load .env file
In config.exs, there is a section that is supposed to load environment variables from `.env` by running `source`. It currently doesn't work because `source` is a shell built-in, not an executable file.

According to kat on discord, it sounds like this auto-load feature isn't used anyway, and maybe never worked, and can just be removed.

I'm still getting my dev environment working and I'm not ready to start submitting PRs yet, but I will plan to come back later and make this change if no one else gets to it first.

### PR DESCRIPTION
**Pull request by EmiSocks**
Since the `.env` configuration file did not seem to be working, this instead adds an Elixir file for setting these variables. It contains the options that one might want to change locally but not commit: database stuff, Stripe, AWS and HTTP port. This should fix #199.

Since it's in `.gitignore`, I've included an example file instead, so the idea is that one would copy `dev.secret.example.exs` into `dev.secret.exs` and modify it. It's intentionally set up so that it fails to run if `dev.secret.exs` does not exist, so that people can't forget to do that, but it should probably be added to the wiki and replace the section about environment variables.

I have tested the variables for HTTP port, database connection and Stripe (at least that it runs and Stripe doesn't complain about it), but not that the AWS variables actually work. They should, but someone should test that.

Also, it only does that import for dev, which is the only environment that matters for this, I think. If the `.env` file was also used in test, maybe a `test.secret.exs` file would be needed too?

### CODE REVIEW

File: config/config.exs [hunk 1]
```diff
@@ -65,3 +54,8 @@ config :stripity_stripe,
 # Import environment specific config. This must remain at the bottom
 # of this file so it overrides the configuration defined above.
 import_config "#{config_env()}.exs"
+
+# Import local development config.
+if config_env() == :dev do
+  import_config "dev.secret.exs"
+end
```
Comment (zkat) [inline config/config.exs:61]: could you move this to `dev.exs`?

**Review by zkat — CHANGES_REQUESTED** [review]

**Comment by zkat** [comment]
looks like you need to run a `mix format`, too.

**Review by zkat — APPROVED** [review]

**Comment by zkat** [comment]
Could you also please sign the CLA (https://github.com/digitalworkersguild/banchan/blob/main/CLA.md#signatures) before I merge this? You can do it as part of this PR.
